-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.branches definition

-- Lookup table for channel_directory.branch. sort_order is the order Main.py processes
-- branches in (see load_channel_directory in modules/Settings.py): each branch's talents
-- oldest debut first, then that branch's official channels. Add a branch by inserting a
-- row -- no code change needed. A fresh database needs these rows before any
-- channel_directory rows can be inserted.

-- Drop table

-- DROP TABLE public.branches;

CREATE TABLE public.branches (
	"name" text NOT NULL,
	sort_order int4 NOT NULL,
	CONSTRAINT pk_branches PRIMARY KEY (name),
	CONSTRAINT branches_sort_order_unique UNIQUE (sort_order)
);


-- NOTE: The *_members tables (emotes_<talent>_members, messages_<talent>_members,
-- nickname_matches_<talent>_members) predate the unified channel_id / channel_directory
-- schema used by emotes, nicknames, nickname_matches, and the partitioned messages table.
-- Members-only chat data still writes to these per-channel tables today. They are kept
-- intentionally -- they hold data that cannot be deleted and are slated to be
-- re-implemented under the unified schema at a later date. Do not drop.

-- public.channel_directory definition

-- color_1/color_2: the channel's two brand colors, used to keep Grafana series colors
-- consistent for a given channel across every panel/dashboard (see "Config from query
-- results" transform usage in Grafana dashboards built against this schema).
--
-- channel_type: 'talent' (a talent's own channel) or 'official' (a branch's main channel,
-- e.g. HoloEN, or a unit's channel, e.g. ReGLOSS). Official channels sit in the branch
-- they belong to; branch-level ones use "group" = 'Branch', unit-level ones use their
-- unit's group. Replaces the old 'Official' pseudo-branch -- see
-- migrate_channel_branches.py.

-- Drop table

-- DROP TABLE public.channel_directory;

CREATE TABLE public.channel_directory (
	"name" text NOT NULL,
	user_id text NOT NULL,
	db_suffix text NOT NULL,
	"group" text NOT NULL,
	color_1 text DEFAULT '#ffffff'::text NOT NULL,
	color_2 text DEFAULT '#ffffff'::text NOT NULL,
	branch text NOT NULL,
	active bool NOT NULL,
	debut date NOT NULL,
	process bool NOT NULL,
	channel_type text DEFAULT 'talent'::text NOT NULL,
	CONSTRAINT channel_directory_unique UNIQUE (user_id),
	CONSTRAINT channel_directory_branches_fk FOREIGN KEY (branch) REFERENCES public.branches(name),
	CONSTRAINT channel_directory_channel_type_check CHECK ((channel_type = ANY (ARRAY['talent'::text, 'official'::text])))
);
