-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- NOTE: The *_members tables (emotes_<talent>_members, messages_<talent>_members,
-- nickname_matches_<talent>_members) predate the unified channel_id / channel_directory
-- schema used by emotes, nicknames, nickname_matches, and the partitioned messages table.
-- Members-only chat data still writes to these per-channel tables today. They are kept
-- intentionally -- they hold data that cannot be deleted and are slated to be
-- re-implemented under the unified schema at a later date. Do not drop.

-- public.channel_directory definition

-- color_1/color_2: the channel's two brand colors, used to keep Grafana series colors
-- consistent for a given channel across every panel/dashboard (see "Config from query
-- results" transform usage in Grafana dashboards built against this schema).

-- Drop table

-- DROP TABLE public.channel_directory;

CREATE TABLE public.channel_directory (
	"name" text NOT NULL,
	user_id text NOT NULL,
	db_suffix text NOT NULL,
	"group" text NOT NULL,
	color_1 text DEFAULT '#ffffff'::text NOT NULL,
	color_2 text DEFAULT '#ffffff'::text NOT NULL,
	CONSTRAINT channel_directory_unique UNIQUE (user_id)
);
