-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.channel_video_summary definition

-- One row per channel_directory entry (LEFT JOIN, so channels with no videos yet show 0s),
-- with video counts and summed duration split by public vs. members-only (videos.members).
-- Durations are hours rounded to the nearest whole hour (videos.duration is seconds).
-- Videos with a NULL duration (still live/upcoming, or missing start/end times) count toward
-- the video totals but add nothing to the hour totals. A plain view rather than a
-- materialized one -- it only aggregates public.videos (tens of thousands of rows), which is
-- cheap enough to compute live on every query.

CREATE OR REPLACE VIEW public.channel_video_summary AS
SELECT cd.name AS channel_name,
    cd.user_id AS channel_id,
    count(v.id) AS total_videos,
    count(v.id) FILTER (WHERE (NOT v.members)) AS public_videos,
    count(v.id) FILTER (WHERE v.members) AS members_videos,
    (round((COALESCE(sum(v.duration), (0)::numeric) / 3600.0)))::bigint AS total_hours,
    (round((COALESCE(sum(v.duration) FILTER (WHERE (NOT v.members)), (0)::numeric) / 3600.0)))::bigint AS public_hours,
    (round((COALESCE(sum(v.duration) FILTER (WHERE v.members), (0)::numeric) / 3600.0)))::bigint AS members_hours
   FROM (channel_directory cd
     LEFT JOIN videos v ON ((v.channel_id = cd.user_id)))
  GROUP BY cd.name, cd.user_id;
