-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.emotes definition

-- Drop table

-- DROP TABLE public.emotes;

CREATE TABLE public.emotes (
	id text NOT NULL,
	"name" text NOT NULL,
	url text NULL,
	custom bool NOT NULL,
	channel_id text NOT NULL,
	CONSTRAINT pk_emotes PRIMARY KEY (channel_id, id),
	CONSTRAINT emotes_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id)
);
