-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.emotes_calli_members definition

-- Drop table

-- DROP TABLE public.emotes_calli_members;

CREATE TABLE public.emotes_calli_members (
	id text NOT NULL,
	"name" text NOT NULL,
	url text NULL,
	custom bool NOT NULL,
	CONSTRAINT idx_emotes_id_calli_members UNIQUE (id)
);


-- public.emotes_ina_members definition

-- Drop table

-- DROP TABLE public.emotes_ina_members;

CREATE TABLE public.emotes_ina_members (
	id text NOT NULL,
	"name" text NOT NULL,
	url text NULL,
	custom bool NOT NULL,
	CONSTRAINT idx_emotes_id_ina_members UNIQUE (id)
);


-- public.emotes_kiara_members definition

-- Drop table

-- DROP TABLE public.emotes_kiara_members;

CREATE TABLE public.emotes_kiara_members (
	id text NOT NULL,
	"name" text NOT NULL,
	url text NULL,
	custom bool NOT NULL,
	CONSTRAINT idx_emotes_id_kiara_members UNIQUE (id)
);
