-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.messages definition

-- Each talent has its own partition of public.messages, keyed by their YouTube channel_id.
-- Partition tables inherit the parent's columns, constraints, and indexes -- they are not
-- redefined per-partition.

-- Drop table

-- DROP TABLE public.messages;

CREATE TABLE public.messages (
	message_id text NOT NULL,
	message text NULL,
	"timestamp" int8 NULL,
	time_in_seconds float4 NULL,
	"type" text NULL,
	video_id text NULL,
	user_id text NULL,
	user_name text NULL,
	user_member_status int8 NULL,
	ismoderator bool DEFAULT false NOT NULL,
	isverified bool DEFAULT false NOT NULL,
	isowner bool DEFAULT false NOT NULL,
	amount float4 NULL,
	currency text NULL,
	symbol text NULL,
	color text NULL,
	datetime timestamp GENERATED ALWAYS AS (
CASE
    WHEN ("timestamp" > '1000000000000000'::bigint) THEN to_timestamp((("timestamp" / 1000000))::double precision)
    ELSE to_timestamp(("timestamp")::double precision)
END) STORED NULL,
	channel_id text NOT NULL,
	CONSTRAINT pk_messages PRIMARY KEY (channel_id, message_id),
	CONSTRAINT messages_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT messages_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user_ids(id),
	CONSTRAINT messages_video_id_fk FOREIGN KEY (video_id) REFERENCES public.videos(id)
)
PARTITION BY LIST (channel_id);

CREATE TABLE public.messages_aki PARTITION OF public.messages FOR VALUES IN ('FTLzh12_nrtzqBPsTCqenA');
CREATE TABLE public.messages_altare PARTITION OF public.messages FOR VALUES IN ('yxtGMdWlURZ30WSnEjDOQw');
CREATE TABLE public.messages_ame PARTITION OF public.messages FOR VALUES IN ('yl1z3jo3XHR1riLFKG5UAg');
CREATE TABLE public.messages_anya PARTITION OF public.messages FOR VALUES IN ('727SQYUvx5pDDGQpTICNWg');
CREATE TABLE public.messages_aokun PARTITION OF public.messages FOR VALUES IN ('MGfV7TVTmHhEErVJg1oHBQ');
CREATE TABLE public.messages_aqua PARTITION OF public.messages FOR VALUES IN ('1opHUrw8rvnsadT-iGp7Cg');
CREATE TABLE public.messages_aruran PARTITION OF public.messages FOR VALUES IN ('KeAhJvy8zgXWbh9duVjIaQ');
CREATE TABLE public.messages_asobi PARTITION OF public.messages FOR VALUES IN ('AHwWUotyS3l2qBetFDsjgQ');
CREATE TABLE public.messages_astel PARTITION OF public.messages FOR VALUES IN ('NVEsYbiZjH5QLmGeSgTSzg');
CREATE TABLE public.messages_axel PARTITION OF public.messages FOR VALUES IN ('2hx0xVkMoHGWijwr_lA01w');
CREATE TABLE public.messages_ayame PARTITION OF public.messages FOR VALUES IN ('7fk0CB07ly8oSl0aqKkqFg');
CREATE TABLE public.messages_azki PARTITION OF public.messages FOR VALUES IN ('0TXe_LYZ4scaW2XMyi5_kw');
CREATE TABLE public.messages_bae PARTITION OF public.messages FOR VALUES IN ('gmPnx-EEeOrZSg5Tiw7ZRQ');
CREATE TABLE public.messages_bettel PARTITION OF public.messages FOR VALUES IN ('HP4f7G2dWD4qib7BMatGAw');
CREATE TABLE public.messages_biboo PARTITION OF public.messages FOR VALUES IN ('9p_lqQ0FEDz327Vgf5JwqA');
CREATE TABLE public.messages_botan PARTITION OF public.messages FOR VALUES IN ('UKD-uaobj9jiqB-VXt71mA');
CREATE TABLE public.messages_calli PARTITION OF public.messages FOR VALUES IN ('L_qhgtOy0dy1Agp8vkySQg');
CREATE TABLE public.messages_ceci PARTITION OF public.messages FOR VALUES IN ('vN5h1ShZtc7nly3pezRayg');
CREATE TABLE public.messages_chihaya PARTITION OF public.messages FOR VALUES IN ('KMWFR6lAstLa7Vbf5dH7ig');
CREATE TABLE public.messages_chloe PARTITION OF public.messages FOR VALUES IN ('IBY1ollUsauvVi4hW4cumw');
CREATE TABLE public.messages_choco PARTITION OF public.messages FOR VALUES IN ('1suqwovbL1kzsoaZgFZLKg');
CREATE TABLE public.messages_coco PARTITION OF public.messages FOR VALUES IN ('S9uQI-jC3DE0L4IpXyvr6w');
CREATE TABLE public.messages_erb PARTITION OF public.messages FOR VALUES IN ('W5uhrG1eCBYditmhL0Ykjw');
CREATE TABLE public.messages_fauna PARTITION OF public.messages FOR VALUES IN ('O_aKKYxn4tvrqPjcTzZ6EQ');
CREATE TABLE public.messages_flare PARTITION OF public.messages FOR VALUES IN ('vInZx9h3jC2JzsIzoOebWg');
CREATE TABLE public.messages_flayon PARTITION OF public.messages FOR VALUES IN ('060r4zABV18vcahAWR1n7w');
CREATE TABLE public.messages_flowglow PARTITION OF public.messages FOR VALUES IN ('u2n3qHuOuQIygREMnWeQWg');
CREATE TABLE public.messages_fubuki PARTITION OF public.messages FOR VALUES IN ('dn5BQ06XqgXoAxIhbqw5Rg');
CREATE TABLE public.messages_fuma PARTITION OF public.messages FOR VALUES IN ('c88OV45ICgHbn3ZqLLb52w');
CREATE TABLE public.messages_fwmc PARTITION OF public.messages FOR VALUES IN ('t9H_RpQzhxzlyBxFqrdHqA');
CREATE TABLE public.messages_gibby PARTITION OF public.messages FOR VALUES IN ('Jv02SHZgav7Mv3V0kBOR8Q');
CREATE TABLE public.messages_gigi PARTITION OF public.messages FOR VALUES IN ('DHABijvPBnJm7F-KlNME3w');
CREATE TABLE public.messages_gura PARTITION OF public.messages FOR VALUES IN ('oSrY_IQQVpmIRZ9Xf-y93g');
CREATE TABLE public.messages_haachama PARTITION OF public.messages FOR VALUES IN ('1CfXB_kRs3C-zaeTG3oGyg');
CREATE TABLE public.messages_hajime PARTITION OF public.messages FOR VALUES IN ('1iA6_NT4mtAcIII6ygrvCw');
CREATE TABLE public.messages_hakka PARTITION OF public.messages FOR VALUES IN ('7gxU6NXjKF1LrgOddPzgTw');
CREATE TABLE public.messages_holoen PARTITION OF public.messages FOR VALUES IN ('otXwY6s8pWmuWd_snKYjhg');
CREATE TABLE public.messages_holoid PARTITION OF public.messages FOR VALUES IN ('frWoRGlawPQDQxxeIDRP0Q');
CREATE TABLE public.messages_hololive PARTITION OF public.messages FOR VALUES IN ('JFZiqLMntJufDCHc6bQixg');
CREATE TABLE public.messages_ina PARTITION OF public.messages FOR VALUES IN ('MwGHR0BTZuLsmjY_NT5Pwg');
CREATE TABLE public.messages_iofi PARTITION OF public.messages FOR VALUES IN ('Aoy6rzhSf4ydcYjJw3WoVg');
CREATE TABLE public.messages_iroha PARTITION OF public.messages FOR VALUES IN ('_vMYWcDjmfdpH6r4TTn1MQ');
CREATE TABLE public.messages_irys PARTITION OF public.messages FOR VALUES IN ('8rcEBzJSleTkf_-agPM20g');
CREATE TABLE public.messages_izuru PARTITION OF public.messages FOR VALUES IN ('ZgOv3YDEs-ZnZWDYVwJdmA');
CREATE TABLE public.messages_jurard PARTITION OF public.messages FOR VALUES IN ('TVSOgYuSWmNAt-lnJPkEEw');
CREATE TABLE public.messages_kaela PARTITION OF public.messages FOR VALUES IN ('ZLZ8Jjx_RN2CXloOmgTHVg');
CREATE TABLE public.messages_kanade PARTITION OF public.messages FOR VALUES IN ('WQtYtq9EOB4-I5P-3fh8lA');
CREATE TABLE public.messages_kanata PARTITION OF public.messages FOR VALUES IN ('ZlDXzGoo7d44bwdNObFacg');
CREATE TABLE public.messages_kiara PARTITION OF public.messages FOR VALUES IN ('Hsx4Hqa-1ORjQTh9TYDhww');
CREATE TABLE public.messages_kira PARTITION OF public.messages FOR VALUES IN ('EzsociuFqVwgZuMaZqaCsg');
CREATE TABLE public.messages_kobo PARTITION OF public.messages FOR VALUES IN ('jLEmnpCNeisMxy134KPwWw');
CREATE TABLE public.messages_korone PARTITION OF public.messages FOR VALUES IN ('hAnqc_AY5_I3Px5dig3X1Q');
CREATE TABLE public.messages_koyori PARTITION OF public.messages FOR VALUES IN ('6eWCld0KwmyHFbAqK3V-Rw');
CREATE TABLE public.messages_kronii PARTITION OF public.messages FOR VALUES IN ('mbs8T6MWqUHP1tIQvSgKrg');
CREATE TABLE public.messages_kyoko PARTITION OF public.messages FOR VALUES IN ('SjQDxud2HkAO2DVD3lwxmw');
CREATE TABLE public.messages_lamy PARTITION OF public.messages FOR VALUES IN ('FKOVgVbGmX65RxO3EtH3iw');
CREATE TABLE public.messages_laplus PARTITION OF public.messages FOR VALUES IN ('ENwRMx5Yh42zWpzURebzTw');
CREATE TABLE public.messages_lui PARTITION OF public.messages FOR VALUES IN ('s9_O1tRPMQTHQ-N_L6FU2g');
CREATE TABLE public.messages_luna PARTITION OF public.messages FOR VALUES IN ('a9Y57gfeY0Zro_noHRVrnw');
CREATE TABLE public.messages_magni PARTITION OF public.messages FOR VALUES IN ('7MMNHR-kf9EN1rXiesMTMw');
CREATE TABLE public.messages_marine PARTITION OF public.messages FOR VALUES IN ('CzUftO8KOVkV4wQG1vkUvg');
CREATE TABLE public.messages_matsuri PARTITION OF public.messages FOR VALUES IN ('Q0UDLQCjY0rmuxCDE38FGg');
CREATE TABLE public.messages_mela PARTITION OF public.messages FOR VALUES IN ('8eitCE9Z6EwUCs-VUi1blg');
CREATE TABLE public.messages_miko PARTITION OF public.messages FOR VALUES IN ('-hM6YJuNYVAmUWxeIr9FeA');
CREATE TABLE public.messages_mio PARTITION OF public.messages FOR VALUES IN ('p-5t9SrOQwXMU7iIjQfARg');
CREATE TABLE public.messages_miyabi PARTITION OF public.messages FOR VALUES IN ('6t3-_N8A6ME1JShZHHqOMw');
CREATE TABLE public.messages_moona PARTITION OF public.messages FOR VALUES IN ('P0BspO_AMEe3aQqqpo89Dg');
CREATE TABLE public.messages_mumei PARTITION OF public.messages FOR VALUES IN ('3n5uGu18FoCy23ggWWp8tA');
CREATE TABLE public.messages_nene PARTITION OF public.messages FOR VALUES IN ('AWSyEs_Io8MtpY3m-zqILA');
CREATE TABLE public.messages_nerissa PARTITION OF public.messages FOR VALUES IN ('_sFNM0z0MWm9A6WlKPuMMg');
CREATE TABLE public.messages_niko PARTITION OF public.messages FOR VALUES IN ('uI_opAVX6qbxZY-a-AxFuQ');
CREATE TABLE public.messages_noel PARTITION OF public.messages FOR VALUES IN ('dyqAaZDKHXg4Ahi7VENThQ');
CREATE TABLE public.messages_octavio PARTITION OF public.messages FOR VALUES IN ('Lk1hcmxg8rJ3Nm1_GvxTRA');
CREATE TABLE public.messages_oga PARTITION OF public.messages FOR VALUES IN ('wL7dgTxKo8Y4RFIKWaf8gA');
CREATE TABLE public.messages_okayu PARTITION OF public.messages FOR VALUES IN ('vaTdHTWBGv3MKj3KVqJVCw');
CREATE TABLE public.messages_ollie PARTITION OF public.messages FOR VALUES IN ('Yz_5n-uDuChHtLo7My1HnQ');
CREATE TABLE public.messages_pekora PARTITION OF public.messages FOR VALUES IN ('1DCedRgGHBdm81E1llLhOQ');
CREATE TABLE public.messages_polka PARTITION OF public.messages FOR VALUES IN ('K9V2B22uJYu3N7eR_BT9QA');
CREATE TABLE public.messages_raden PARTITION OF public.messages FOR VALUES IN ('dXAk5MpyLD8594lm_OvtGQ');
CREATE TABLE public.messages_raora PARTITION OF public.messages FOR VALUES IN ('l69AEx4MdqMZH7Jtsm7Tig');
CREATE TABLE public.messages_regloss PARTITION OF public.messages FOR VALUES IN ('10wVt6hoQiwySRhz7RdOUA');
CREATE TABLE public.messages_reine PARTITION OF public.messages FOR VALUES IN ('hgTyjG-pdNvxxhdsXfHQ5Q');
CREATE TABLE public.messages_rikka PARTITION OF public.messages FOR VALUES IN ('9mf_ZVpouoILRY9NUIaK-w');
CREATE TABLE public.messages_rio PARTITION OF public.messages FOR VALUES IN ('dfMHxjcCc2HSd9qFvfJgjg');
CREATE TABLE public.messages_riona PARTITION OF public.messages FOR VALUES IN ('9LSiN9hXI55svYEBrrK-tw');
CREATE TABLE public.messages_ririka PARTITION OF public.messages FOR VALUES IN ('tyWhCj3AqKh2dXctLkDtng');
CREATE TABLE public.messages_risu PARTITION OF public.messages FOR VALUES IN ('OyYb1c43VlX9rc_lT6NKQw');
CREATE TABLE public.messages_roberu PARTITION OF public.messages FOR VALUES IN ('ANDOlYTJT7N5jlRC3zfzVA');
CREATE TABLE public.messages_roboco PARTITION OF public.messages FOR VALUES IN ('DqI2jOz0weumE8s7paEk6g');
CREATE TABLE public.messages_ruze PARTITION OF public.messages FOR VALUES IN ('ajbFh6e_R8QZdHAMbbi4rQ');
CREATE TABLE public.messages_sana PARTITION OF public.messages FOR VALUES IN ('sUj0dszADCGbF3gNrQEuSQ');
CREATE TABLE public.messages_shien PARTITION OF public.messages FOR VALUES IN ('hSvpZYRPh0FvG4SJGSga3g');
CREATE TABLE public.messages_shinri PARTITION OF public.messages FOR VALUES IN ('MqGG8BRAiI1lJfKOpETM_w');
CREATE TABLE public.messages_shion PARTITION OF public.messages FOR VALUES IN ('XTpFs_3PqI41qX2d9tL2Rw');
CREATE TABLE public.messages_shiori PARTITION OF public.messages FOR VALUES IN ('gnfPPb9JI3e9A4cXHnWbyg');
CREATE TABLE public.messages_sopia PARTITION OF public.messages FOR VALUES IN ('ROQtXcp2loQEmvpe5rhJzQ');
CREATE TABLE public.messages_sora PARTITION OF public.messages FOR VALUES IN ('p6993wxpyDPHUpavwDFqgg');
CREATE TABLE public.messages_starsen PARTITION OF public.messages FOR VALUES IN ('JxZpzx4wHzEYD-eCiZPikg');
CREATE TABLE public.messages_subaru PARTITION OF public.messages FOR VALUES IN ('vzGlP9oQwU--Y0r9id_jnA');
CREATE TABLE public.messages_suchan PARTITION OF public.messages FOR VALUES IN ('jk2nKmHzgH5Xy-C5qYRd5A');
CREATE TABLE public.messages_suisei PARTITION OF public.messages FOR VALUES IN ('5CwaMl1eIgY8h02uZw7u8A');
CREATE TABLE public.messages_temma PARTITION OF public.messages FOR VALUES IN ('GNI4MENvnsymYjKiZwv9eg');
CREATE TABLE public.messages_towa PARTITION OF public.messages FOR VALUES IN ('1uv2Oq6kNxgATlCiez59hw');
CREATE TABLE public.messages_tsuzuri PARTITION OF public.messages FOR VALUES IN ('y9mgxB8pn2C4aNK_MPthDQ');
CREATE TABLE public.messages_uyu PARTITION OF public.messages FOR VALUES IN ('gRqGV1gBf2Esxh0Tz1vxzw');
CREATE TABLE public.messages_vesper PARTITION OF public.messages FOR VALUES IN ('DRWSO281bIHYVi-OV3iFYA');
CREATE TABLE public.messages_vivi PARTITION OF public.messages FOR VALUES IN ('GzTVXqMQHa4AgJVJIVvtDQ');
CREATE TABLE public.messages_watame PARTITION OF public.messages FOR VALUES IN ('qm3BQLlJfvkTsX_hvm0UmA');
CREATE TABLE public.messages_zeta PARTITION OF public.messages FOR VALUES IN ('TvHWSfBZgtxE4sILOaurIQ');
-- idx_messages_video_user_status and idx_messages_user_timestamp were added by
-- sql/video_message_stats.sql to make its one-time backfill (and future ad-hoc
-- reconciliation queries) feasible against the 200M+ row table. Not yet attached on the
-- messages_holoen partition -- see conversation notes.
CREATE INDEX idx_messages_datetime ON ONLY public.messages USING btree (datetime);
CREATE INDEX idx_messages_message_text ON ONLY public.messages USING btree (message) WHERE (message ~ ':[a-zA-Z0-9_-]+:'::text);
CREATE INDEX idx_messages_null ON ONLY public.messages USING btree (message) WHERE (message IS NOT NULL);
CREATE INDEX idx_messages_user_id ON ONLY public.messages USING btree (user_id);
CREATE INDEX idx_messages_user_timestamp ON ONLY public.messages USING btree (user_id, "timestamp") INCLUDE (video_id);
CREATE INDEX idx_messages_video_id ON ONLY public.messages USING btree (video_id);
CREATE INDEX idx_messages_video_user_status ON ONLY public.messages USING btree (video_id, user_id) INCLUDE (user_member_status);
