-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.messages definition

-- Each talent has its own partition of public.messages, keyed by their YouTube channel_id.
-- Partition tables inherit the parent's columns, constraints, and indexes -- they are not
-- redefined per-partition.

-- Drop table

-- DROP TABLE public.messages;

CREATE TABLE public.messages (
	message_id text NOT NULL,
	message text NULL,
	"timestamp" int8 NULL,
	time_in_seconds float4 NULL,
	"type" text NULL,
	video_id text NULL,
	user_id text NULL,
	user_name text NULL,
	user_member_status int8 NULL,
	ismoderator bool DEFAULT false NOT NULL,
	isverified bool DEFAULT false NOT NULL,
	isowner bool DEFAULT false NOT NULL,
	amount float4 NULL,
	currency text NULL,
	symbol text NULL,
	color text NULL,
	datetime timestamp GENERATED ALWAYS AS (
CASE
    WHEN ("timestamp" > '1000000000000000'::bigint) THEN to_timestamp((("timestamp" / 1000000))::double precision)
    ELSE to_timestamp(("timestamp")::double precision)
END) STORED NULL,
	channel_id text NOT NULL,
	CONSTRAINT pk_messages PRIMARY KEY (channel_id, message_id),
	CONSTRAINT messages_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT messages_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user_ids(id),
	CONSTRAINT messages_video_id_fk FOREIGN KEY (video_id) REFERENCES public.videos(id)
)
PARTITION BY LIST (channel_id);

CREATE TABLE public.messages_ame PARTITION OF public.messages FOR VALUES IN ('yl1z3jo3XHR1riLFKG5UAg');
CREATE TABLE public.messages_bae PARTITION OF public.messages FOR VALUES IN ('gmPnx-EEeOrZSg5Tiw7ZRQ');
CREATE TABLE public.messages_biboo PARTITION OF public.messages FOR VALUES IN ('9p_lqQ0FEDz327Vgf5JwqA');
CREATE TABLE public.messages_calli PARTITION OF public.messages FOR VALUES IN ('L_qhgtOy0dy1Agp8vkySQg');
CREATE TABLE public.messages_ceci PARTITION OF public.messages FOR VALUES IN ('vN5h1ShZtc7nly3pezRayg');
CREATE TABLE public.messages_erb PARTITION OF public.messages FOR VALUES IN ('W5uhrG1eCBYditmhL0Ykjw');
CREATE TABLE public.messages_fauna PARTITION OF public.messages FOR VALUES IN ('O_aKKYxn4tvrqPjcTzZ6EQ');
CREATE TABLE public.messages_fwmc PARTITION OF public.messages FOR VALUES IN ('t9H_RpQzhxzlyBxFqrdHqA');
CREATE TABLE public.messages_gigi PARTITION OF public.messages FOR VALUES IN ('DHABijvPBnJm7F-KlNME3w');
CREATE TABLE public.messages_gura PARTITION OF public.messages FOR VALUES IN ('oSrY_IQQVpmIRZ9Xf-y93g');
CREATE TABLE public.messages_holoen PARTITION OF public.messages FOR VALUES IN ('otXwY6s8pWmuWd_snKYjhg');
CREATE TABLE public.messages_ina PARTITION OF public.messages FOR VALUES IN ('MwGHR0BTZuLsmjY_NT5Pwg');
CREATE TABLE public.messages_irys PARTITION OF public.messages FOR VALUES IN ('8rcEBzJSleTkf_-agPM20g');
CREATE TABLE public.messages_kiara PARTITION OF public.messages FOR VALUES IN ('Hsx4Hqa-1ORjQTh9TYDhww');
CREATE TABLE public.messages_kronii PARTITION OF public.messages FOR VALUES IN ('mbs8T6MWqUHP1tIQvSgKrg');
CREATE TABLE public.messages_moona PARTITION OF public.messages FOR VALUES IN ('P0BspO_AMEe3aQqqpo89Dg');
CREATE TABLE public.messages_mumei PARTITION OF public.messages FOR VALUES IN ('3n5uGu18FoCy23ggWWp8tA');
CREATE TABLE public.messages_nerissa PARTITION OF public.messages FOR VALUES IN ('_sFNM0z0MWm9A6WlKPuMMg');
CREATE TABLE public.messages_raora PARTITION OF public.messages FOR VALUES IN ('l69AEx4MdqMZH7Jtsm7Tig');
CREATE TABLE public.messages_sana PARTITION OF public.messages FOR VALUES IN ('sUj0dszADCGbF3gNrQEuSQ');
CREATE TABLE public.messages_shiori PARTITION OF public.messages FOR VALUES IN ('gnfPPb9JI3e9A4cXHnWbyg');
-- idx_messages_video_user_status and idx_messages_user_timestamp were added by
-- sql/video_message_stats.sql to make its one-time backfill (and future ad-hoc
-- reconciliation queries) feasible against the 200M+ row table. Not yet attached on the
-- messages_holoen partition -- see conversation notes.
CREATE INDEX idx_messages_datetime ON ONLY public.messages USING btree (datetime);
CREATE INDEX idx_messages_message_text ON ONLY public.messages USING btree (message) WHERE (message ~ ':[a-zA-Z0-9_-]+:'::text);
CREATE INDEX idx_messages_null ON ONLY public.messages USING btree (message) WHERE (message IS NOT NULL);
CREATE INDEX idx_messages_user_id ON ONLY public.messages USING btree (user_id);
CREATE INDEX idx_messages_user_timestamp ON ONLY public.messages USING btree (user_id, "timestamp") INCLUDE (video_id);
CREATE INDEX idx_messages_video_id ON ONLY public.messages USING btree (video_id);
CREATE INDEX idx_messages_video_user_status ON ONLY public.messages USING btree (video_id, user_id) INCLUDE (user_member_status);
