-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.nickname_matches_kiara_members definition

-- Drop table

-- DROP TABLE public.nickname_matches_kiara_members;

CREATE TABLE public.nickname_matches_kiara_members (
	matched_nickname text NULL,
	message_id text NULL,
	index_start int8 NULL,
	index_end int8 NULL,
	CONSTRAINT unq_message_id_index_start_index_end_kiara_members UNIQUE (message_id, index_start, index_end),
	CONSTRAINT fk_nickname_matches_message_id_messages_message_id_kiara_member FOREIGN KEY (message_id) REFERENCES public.messages_kiara_members(message_id)
);
CREATE INDEX idx_nickname_matches_message_id_kiara_members ON public.nickname_matches_kiara_members USING btree (message_id);
