-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.refresh_state definition

-- Change-detection bookkeeping for the once-per-run rebuilds at the end of Main.py
-- (refresh_first_message_counts(), refresh_user_message_rankings(), refresh_user_summary()).
-- One row per rebuild: change_count is the summed n_tup_ins + n_tup_upd + n_tup_del from
-- pg_stat_user_tables across that rebuild's source tables, snapshotted just before its last
-- successful run. If the current sum still matches, nothing the rebuild reads has changed and
-- it's skipped -- see RefreshRollupsIfChanged in modules/Database.py for the source-table lists.
-- Any difference (including a lower sum after a stats reset/crash) triggers a rebuild. Delete a
-- row to force that rebuild on the next run.

-- Drop table

-- DROP TABLE public.refresh_state;

CREATE TABLE public.refresh_state (
	refresh_name text NOT NULL,
	change_count int8 NOT NULL,
	refreshed_at timestamp DEFAULT now() NOT NULL,
	CONSTRAINT refresh_state_pkey PRIMARY KEY (refresh_name)
);
