-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- Auto-generated (ASR) caption cues for public videos, one row per cue. Parsed
-- from the WebVTT file yt-dlp writes for a video's automatic_captions -- see
-- YT_API.Get_Subtitles in modules/Classes.py. WebVTT (not YouTube's undocumented
-- json3 format) was chosen specifically for long-term stability -- it's a W3C
-- standard and yt-dlp's most mature extraction path for YouTube captions.
-- Unpartitioned (unlike messages): cue volume per video (a few thousand for a
-- long VOD) is orders of magnitude below chat's 200M+ row scale, so a single
-- indexed table is sufficient -- channel_id is still present so this could be
-- partitioned later without a schema change if that assumption ever proves wrong.
-- Members-only subtitle data mirrors the messages_<talent>_members split (own
-- flat per-talent tables, no channel_id) rather than a channel_directory-style
-- unified table + boolean column, to stay consistent with how messages/emotes
-- already separate members-only data.

-- public.subtitles definition

-- Drop table

-- DROP TABLE public.subtitles;

CREATE TABLE public.subtitles (
	channel_id text NOT NULL,
	video_id text NOT NULL,
	language text DEFAULT 'en'::text NOT NULL,
	seq int4 NOT NULL,
	start_ms int8 NOT NULL,
	end_ms int8 NOT NULL,
	text text NOT NULL,
	CONSTRAINT pk_subtitles PRIMARY KEY (channel_id, video_id, language, seq),
	CONSTRAINT subtitles_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT subtitles_video_id_fk FOREIGN KEY (video_id) REFERENCES public.videos(id)
);
CREATE INDEX idx_subtitles_video_id ON public.subtitles USING btree (video_id);
