-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.user_first_message definition

-- Pointer: the earliest message (by timestamp) this user has ever sent, across every channel.
-- channel_id/message_id carry a composite FK into messages(channel_id, message_id) -- video_id
-- is deliberately not stored here (join through message_id when needed); this closes a gap
-- where the old video_id-only FK never verified the video actually belonged to this row's
-- channel. timestamp is kept alongside message_id (not dropped) so record_message_stats()'s
-- per-message "is this earlier than what's stored" check stays a cheap in-row comparison
-- instead of a join into messages on every single call.

-- Drop table

-- DROP TABLE public.user_first_message;

CREATE TABLE public.user_first_message (
	user_id text NOT NULL,
	"timestamp" float8 NOT NULL,
	channel_id text NOT NULL,
	message_id text NOT NULL,
	CONSTRAINT user_first_message_pkey PRIMARY KEY (user_id),
	CONSTRAINT user_first_message_message_fkey FOREIGN KEY (channel_id, message_id) REFERENCES public.messages(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_1 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_mumei(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_10 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_kronii(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_11 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_ina(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_12 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_fauna(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_13 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_gura(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_14 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_holoen(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_15 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_nerissa(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_16 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_sana(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_17 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_fwmc(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_18 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_ceci(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_19 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_erb(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_2 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_irys(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_20 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_ame(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_21 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_moona(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_3 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_biboo(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_4 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_gigi(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_5 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_bae(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_6 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_shiori(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_7 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_kiara(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_8 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_raora(channel_id, message_id),
	CONSTRAINT user_first_message_message_fkey_9 FOREIGN KEY (channel_id, message_id) REFERENCES public.messages_calli(channel_id, message_id),
	CONSTRAINT user_first_message_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_ids(id)
);


-- public.user_channel_activity definition

-- Per-user, per-channel/talent activity rollup (renamed from user_first_channel_message --
-- it holds far more than a first-message pointer now). first_message_id/timestamp point to
-- this user's earliest message in this channel (message_id carries a composite FK into
-- messages(channel_id, message_id); timestamp is kept alongside it for the same cheap-comparison
-- reason as user_first_message, above). total_messages, last_message_ts, and max_member_status
-- track running totals, last-seen timestamp, and highest membership tier (user_member_status)
-- ever observed in this channel. emote_count is a running total of emote usages (accurate only
-- from the day this column shipped -- historical emote usage was never persisted per-message,
-- so pre-existing rows start at 0 and there is no backfill for it). ever_moderator/ever_verified/
-- ever_owner are OR-folded permanently ("has this user ever held this status in this channel");
-- last_is_moderator/last_is_verified/last_is_owner are overwritten alongside last_message_ts
-- ("as of their most recent message") -- last_message_ts itself deliberately stays a raw
-- timestamp rather than a message_id pointer, since it updates on every single message (not
-- just first-time-per-user like the pointer above), and a join-based lookup on that path would
-- regress the single hottest write in this schema. Maintained incrementally by
-- public.record_message_stats() (same table update as the first-message pointer, one row per
-- chat message) -- see sql/user_channel_activity_stats.sql for the full DDL, maintenance
-- function, and one-time backfill.

-- Drop table

-- DROP TABLE public.user_channel_activity;

CREATE TABLE public.user_channel_activity (
	channel_id text NOT NULL,
	user_id text NOT NULL,
	"timestamp" float8 NOT NULL,
	total_messages int8 DEFAULT 0 NOT NULL,
	last_message_ts float8 NOT NULL,
	max_member_status int8 NULL,
	first_message_id text NOT NULL,
	emote_count int8 DEFAULT 0 NOT NULL,
	ever_moderator bool DEFAULT false NOT NULL,
	ever_verified bool DEFAULT false NOT NULL,
	ever_owner bool DEFAULT false NOT NULL,
	last_is_moderator bool DEFAULT false NOT NULL,
	last_is_verified bool DEFAULT false NOT NULL,
	last_is_owner bool DEFAULT false NOT NULL,
	CONSTRAINT user_channel_activity_pkey PRIMARY KEY (channel_id, user_id),
	CONSTRAINT user_channel_activity_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT user_channel_activity_message_fkey FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_1 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_mumei(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_10 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_kronii(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_11 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_ina(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_12 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_fauna(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_13 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_gura(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_14 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_holoen(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_15 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_nerissa(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_16 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_sana(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_17 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_fwmc(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_18 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_ceci(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_19 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_erb(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_2 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_irys(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_20 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_ame(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_21 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_moona(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_3 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_biboo(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_4 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_gigi(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_5 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_bae(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_6 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_shiori(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_7 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_kiara(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_8 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_raora(channel_id, message_id),
	CONSTRAINT user_channel_activity_message_fkey_9 FOREIGN KEY (channel_id, first_message_id) REFERENCES public.messages_calli(channel_id, message_id),
	CONSTRAINT user_channel_activity_user_ids_fk FOREIGN KEY (user_id) REFERENCES public.user_ids(id)
);
CREATE INDEX idx_user_channel_activity_channel_totals ON public.user_channel_activity USING btree (channel_id, total_messages DESC);


-- public.refresh_first_message_counts definition

-- Recomputes video_message_stats.first_messages/first_channel_messages from scratch by
-- aggregating user_first_message/user_channel_activity, joining each through to messages via
-- message_id/first_message_id to recover video_id (neither table stores video_id directly --
-- see their own NARRATIVE entries). Call once per full bot run (see RefreshFirstMessageCounts
-- in modules/Database.py and its call at the end of Main.py) -- these columns are no longer
-- patched incrementally per-message (see record_message_stats()).

CREATE OR REPLACE FUNCTION public.refresh_first_message_counts()
 RETURNS void
 LANGUAGE sql
AS $function$
            UPDATE public.video_message_stats SET first_messages = 0, first_channel_messages = 0
            WHERE first_messages != 0 OR first_channel_messages != 0;

            UPDATE public.video_message_stats vms
            SET first_messages = fg.cnt
            FROM (
                SELECT m.video_id, COUNT(*) AS cnt
                FROM public.user_first_message ufm
                JOIN public.messages m ON m.channel_id = ufm.channel_id AND m.message_id = ufm.message_id
                GROUP BY m.video_id
            ) fg
            WHERE fg.video_id = vms.video_id;

            UPDATE public.video_message_stats vms
            SET first_channel_messages = fc.cnt
            FROM (
                SELECT m.video_id, COUNT(*) AS cnt
                FROM public.user_channel_activity uca
                JOIN public.messages m ON m.channel_id = uca.channel_id AND m.message_id = uca.first_message_id
                GROUP BY m.video_id
            ) fc
            WHERE fc.video_id = vms.video_id;
        $function$;
