-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.user_ids definition

-- Drop table

-- DROP TABLE public.user_ids;

CREATE TABLE public.user_ids (
	id text NOT NULL,
	latest_name text NULL,
	custom_url text NULL,
	viewcount int8 NULL,
	subscribers int8 NULL,
	region text NULL,
	processed bool DEFAULT false NOT NULL,
	"exists" bool DEFAULT true NOT NULL,
	created timestamp NULL,
	CONSTRAINT pk_user_ids_id PRIMARY KEY (id)
);
CREATE INDEX idx_user_ids_created ON public.user_ids USING btree (created);
CREATE INDEX idx_user_ids_subscribers ON public.user_ids USING btree (subscribers);
CREATE INDEX idx_user_ids_viewcount ON public.user_ids USING btree (viewcount);
