-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.user_message_rankings definition

-- Per-channel message-count leaderboard rank (channel_rank, partitioned by channel_id, by total
-- message count, RANK() so ties share a rank and the next rank skips). One row per (channel,
-- user) pair. Global rank across all channels combined lives in its own materialized view
-- instead -- public.user_global_message_rankings, below -- to avoid repeating the same global
-- total/rank across every channel row for a multi-channel user (~20 duplicate rows for an
-- active user).
--
-- A MATERIALIZED VIEW rather than a plain view or an incrementally-maintained column -- a
-- single new message can shift every other user's rank in that channel, so there's no single
-- row to touch incrementally, and live-querying it directly took ~20-27s on this server
-- (window-function sort spilling to disk over the ~6.5M row rollup table). Refreshed once per
-- bot run via public.refresh_user_message_rankings() (defined in
-- sql/user_global_message_rankings.sql, since it refreshes both rankings views together) -- see
-- modules/Database.py's RefreshUserMessageRankings() and its call at the end of Main.py -- using
-- REFRESH ... CONCURRENTLY so readers aren't locked out mid-refresh. See
-- sql/user_message_rankings.sql for the full DDL.

CREATE MATERIALIZED VIEW public.user_message_rankings AS
SELECT channel_id,
    user_id,
    total_messages AS channel_messages,
    rank() OVER (PARTITION BY channel_id ORDER BY total_messages DESC) AS channel_rank
   FROM user_channel_activity;
CREATE UNIQUE INDEX idx_user_message_rankings_pk ON public.user_message_rankings USING btree (channel_id, user_id);


-- public.user_global_message_rankings definition

-- Global message-count leaderboard rank for each user across all channels combined
-- (global_rank, RANK() over the summed total, one row per user). Split out from
-- user_message_rankings so each user's global total/rank is stored once instead of once per
-- channel they've posted in. Same MATERIALIZED VIEW rationale (rank isn't incrementally
-- maintainable per-message; live-querying is too slow for a frequently-refreshed dashboard).
-- Refreshed together with user_message_rankings by public.refresh_user_message_rankings() --
-- see sql/user_global_message_rankings.sql for the full DDL.

CREATE MATERIALIZED VIEW public.user_global_message_rankings AS
WITH global_totals AS (
         SELECT user_channel_activity.user_id,
            sum(user_channel_activity.total_messages) AS global_messages
           FROM user_channel_activity
          GROUP BY user_channel_activity.user_id
        )
 SELECT user_id,
    global_messages,
    rank() OVER (ORDER BY global_messages DESC) AS global_rank
   FROM global_totals;
CREATE UNIQUE INDEX idx_user_global_message_rankings_pk ON public.user_global_message_rankings USING btree (user_id);


-- public.refresh_user_message_rankings definition

-- Refreshes both message-count leaderboard materialized views (user_message_rankings,
-- user_global_message_rankings). Call once per full bot run (see RefreshUserMessageRankings in
-- modules/Database.py and its call at the end of Main.py) -- a leaderboard rank isn't
-- incrementally maintainable the way a total/count is, since one new message can shift every
-- other user's rank. Uses CONCURRENTLY so readers (e.g. Grafana) aren't locked out mid-refresh.

CREATE OR REPLACE FUNCTION public.refresh_user_message_rankings()
 RETURNS void
 LANGUAGE sql
AS $function$
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.user_message_rankings;
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.user_global_message_rankings;
$function$;
