-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.user_first_message definition

-- Pointer: the earliest message (by timestamp) this user has ever sent, across every channel.

-- Drop table

-- DROP TABLE public.user_first_message;

CREATE TABLE public.user_first_message (
	user_id text NOT NULL,
	video_id text NOT NULL,
	"timestamp" float8 NOT NULL,
	CONSTRAINT user_first_message_pkey PRIMARY KEY (user_id),
	CONSTRAINT user_first_message_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_ids(id),
	CONSTRAINT user_first_message_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id)
);


-- public.user_first_channel_message definition

-- Per-user, per-channel/talent rollup: video_id/timestamp point to this user's earliest
-- message in this channel; total_messages, last_message_ts, and max_member_status track their
-- running totals, last-seen timestamp, and highest membership tier (user_member_status) ever
-- observed in this channel. Maintained incrementally by public.record_message_stats() (same
-- table update as the first-message pointer, one row per chat message) -- see
-- sql/user_first_channel_message_stats.sql for the full DDL, maintenance function, and
-- one-time backfill.

-- Drop table

-- DROP TABLE public.user_first_channel_message;

CREATE TABLE public.user_first_channel_message (
	channel_id text NOT NULL,
	user_id text NOT NULL,
	video_id text NOT NULL,
	"timestamp" float8 NOT NULL,
	total_messages int8 DEFAULT 0 NOT NULL,
	last_message_ts float8 NOT NULL,
	max_member_status int8 NULL,
	CONSTRAINT user_first_channel_message_pkey PRIMARY KEY (channel_id, user_id),
	CONSTRAINT user_first_channel_message_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT user_first_channel_message_user_ids_fk FOREIGN KEY (user_id) REFERENCES public.user_ids(id),
	CONSTRAINT user_first_channel_message_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id)
);
CREATE INDEX idx_user_first_channel_message_channel_totals ON public.user_first_channel_message USING btree (channel_id, total_messages DESC);


-- public.refresh_first_message_counts definition

-- Recomputes video_message_stats.first_messages/first_channel_messages from scratch by
-- aggregating user_first_message/user_first_channel_message. Call once per full bot run (see
-- RefreshFirstMessageCounts in modules/Database.py and its call at the end of Main.py) --
-- these columns are no longer patched incrementally per-message (see record_message_stats()).

CREATE OR REPLACE FUNCTION public.refresh_first_message_counts()
 RETURNS void
 LANGUAGE sql
AS $function$
    UPDATE public.video_message_stats SET first_messages = 0, first_channel_messages = 0
    WHERE first_messages != 0 OR first_channel_messages != 0;

    UPDATE public.video_message_stats vms
    SET first_messages = fg.cnt
    FROM (SELECT video_id, COUNT(*) AS cnt FROM public.user_first_message GROUP BY video_id) fg
    WHERE fg.video_id = vms.video_id;

    UPDATE public.video_message_stats vms
    SET first_channel_messages = fc.cnt
    FROM (SELECT video_id, COUNT(*) AS cnt FROM public.user_first_channel_message GROUP BY video_id) fc
    WHERE fc.video_id = vms.video_id;
$function$;
