-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.user_channel_superchats definition

-- Per-user, per-channel superchat totals, kept per-currency (channel_id, user_id, currency) --
-- deliberately NOT collapsed into one amount, since summing raw amounts across different
-- currencies would be meaningless. Maintained incrementally by public.record_message_stats()
-- whenever a message carries a non-null amount; fully backfillable from messages.amount/currency
-- (unlike user_channel_activity.emote_count) since those columns already existed per-message.

-- Drop table

-- DROP TABLE public.user_channel_superchats;

CREATE TABLE public.user_channel_superchats (
	channel_id text NOT NULL,
	user_id text NOT NULL,
	currency text NOT NULL,
	superchat_count int8 DEFAULT 0 NOT NULL,
	total_amount float8 DEFAULT 0 NOT NULL,
	CONSTRAINT user_channel_superchats_pkey PRIMARY KEY (channel_id, user_id, currency),
	CONSTRAINT user_channel_superchats_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT user_channel_superchats_user_ids_fk FOREIGN KEY (user_id) REFERENCES public.user_ids(id)
);
CREATE INDEX idx_user_channel_superchats_channel_totals ON public.user_channel_superchats USING btree (channel_id, total_amount DESC);
