-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.user_summary definition

-- One row per user, combining identity (user_ids), global activity (user_first_message,
-- user_global_message_rankings), and per-channel rollups (user_channel_activity,
-- user_channel_superchats) into a single summary. A MATERIALIZED VIEW, not a plain one --
-- it started as a plain view (only the small per-channel rollups, not the 200M+ row messages
-- table, get aggregated), but a sorted top-N query still took 60-90s live: the channel_agg
-- CTE's GROUP BY user_id has no supporting index over the 6.5M-row user_channel_activity
-- table, so Postgres fell back to an external merge sort spilling ~1.7GB to disk on every
-- query. Refreshed once per bot run via public.refresh_user_summary(), after
-- refresh_user_message_rankings() (user_summary reads user_global_message_rankings, so it
-- must be refreshed after that matview is current) -- see modules/Database.py's
-- RefreshUserSummary() and its call at the end of Main.py -- using REFRESH ... CONCURRENTLY
-- so readers aren't locked out mid-refresh. Multi-currency superchat totals are exposed as a
-- jsonb map ({"USD": {"count": N, "total_amount": X}, ...}) rather than a second matview,
-- since collapsing different currencies into one number would be meaningless --
-- user_channel_superchats stays directly queryable for a per-channel/per-currency breakdown.

CREATE MATERIALIZED VIEW public.user_summary AS
WITH channel_agg AS (
         SELECT user_channel_activity.user_id,
            count(DISTINCT user_channel_activity.channel_id) AS channels_active_in,
            max(user_channel_activity.last_message_ts) AS last_message_ts,
            max(user_channel_activity.max_member_status) AS max_member_status,
            bool_or(user_channel_activity.ever_moderator) AS ever_moderator,
            bool_or(user_channel_activity.ever_verified) AS ever_verified,
            bool_or(user_channel_activity.ever_owner) AS ever_owner,
            sum(user_channel_activity.emote_count) AS total_emotes
           FROM user_channel_activity
          GROUP BY user_channel_activity.user_id
        ), superchat_agg AS (
         SELECT per_currency.user_id,
            sum(per_currency.superchat_count) AS total_superchat_count,
            jsonb_object_agg(per_currency.currency, jsonb_build_object('count', per_currency.superchat_count, 'total_amount', per_currency.total_amount)) AS superchats_by_currency
           FROM ( SELECT user_channel_superchats.user_id,
                    user_channel_superchats.currency,
                    sum(user_channel_superchats.superchat_count) AS superchat_count,
                    sum(user_channel_superchats.total_amount) AS total_amount
                   FROM user_channel_superchats
                  GROUP BY user_channel_superchats.user_id, user_channel_superchats.currency) per_currency
          GROUP BY per_currency.user_id
        )
 SELECT u.id AS user_id,
    u.latest_name,
    u.custom_url,
    ufm.channel_id AS first_channel_id,
    ufm.message_id AS first_message_id,
    ufm."timestamp" AS first_message_ts,
    ugmr.global_messages,
    ugmr.global_rank,
    ca.channels_active_in,
    ca.last_message_ts,
    ca.max_member_status,
    ca.ever_moderator,
    ca.ever_verified,
    ca.ever_owner,
    COALESCE(ca.total_emotes, (0)::numeric) AS total_emotes,
    COALESCE(sa.total_superchat_count, (0)::numeric) AS total_superchat_count,
    sa.superchats_by_currency
   FROM ((((user_ids u
     LEFT JOIN user_first_message ufm ON ((ufm.user_id = u.id)))
     LEFT JOIN user_global_message_rankings ugmr ON ((ugmr.user_id = u.id)))
     LEFT JOIN channel_agg ca ON ((ca.user_id = u.id)))
     LEFT JOIN superchat_agg sa ON ((sa.user_id = u.id)));
CREATE UNIQUE INDEX idx_user_summary_pk ON public.user_summary USING btree (user_id);


-- public.refresh_user_summary definition

-- Refreshes the user_summary materialized view. Call once per full bot run, after
-- refresh_user_message_rankings() (see RefreshUserSummary in modules/Database.py and its call
-- at the end of Main.py, right after RefreshUserMessageRankings) -- user_summary reads from
-- user_global_message_rankings, so it must be refreshed after that matview is current. See
-- user_summary's own NARRATIVE entry for why it's a materialized view rather than a plain one.
-- Uses CONCURRENTLY so readers (e.g. Grafana) aren't locked out mid-refresh.

CREATE OR REPLACE FUNCTION public.refresh_user_summary()
 RETURNS void
 LANGUAGE sql
AS $function$
            REFRESH MATERIALIZED VIEW CONCURRENTLY public.user_summary;
        $function$;
