-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- Per-video, per-language subtitle stats. Unlike video_message_stats, this is populated in one
-- shot (not incrementally per-row) by public.record_subtitle_stats(), called right after
-- Get_Subtitles (modules/Classes.py) finishes writing a video's cues for one language --
-- subtitles arrive as a single batch per video/language (unlike chat, which streams in message
-- by message), so there's no need for a running per-cue upsert. See modules/Database.py's
-- RecordSubtitleStats() for the call site. total_subtitles/subtitles_per_min mirror
-- video_message_stats' total_messages/messages_per_min. total_words/words_per_min are a
-- better proxy for actual speaking pace than cue count, since cue segmentation is an artifact
-- of YouTube's ASR chunking, not of how much was said. speech_duration_ms/speech_coverage_pct
-- (sum of each cue's end_ms - start_ms, vs. the video's total duration) flag how much of a
-- video was actually talked over versus silence/music/gameplay-only stretches.

-- public.video_subtitle_stats definition

-- Drop table

-- DROP TABLE public.video_subtitle_stats;

CREATE TABLE public.video_subtitle_stats (
	video_id text NOT NULL,
	channel_id text NOT NULL,
	language text NOT NULL,
	total_subtitles int8 DEFAULT 0 NOT NULL,
	total_words int8 DEFAULT 0 NOT NULL,
	speech_duration_ms int8 DEFAULT 0 NOT NULL,
	subtitles_per_min numeric NULL,
	words_per_min numeric NULL,
	speech_coverage_pct numeric NULL,
	CONSTRAINT video_subtitle_stats_pkey PRIMARY KEY (video_id, language),
	CONSTRAINT video_subtitle_stats_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id),
	CONSTRAINT video_subtitle_stats_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id)
);


-- public.record_subtitle_stats definition

-- Upserts one video/language's row from precomputed totals (cue count, word count, summed cue
-- duration) rather than aggregating public.subtitles itself -- Get_Subtitles already has the
-- parsed cue list in memory right before it writes them, so passing the totals through avoids
-- a redundant read-back query. Division-by-null-duration (video not yet finished) is guarded
-- the same way finalize_video_message_rate() guards it, though in practice this is only ever
-- called after a video's end_time (and therefore duration) is already set -- Subtitles.py only
-- fetches captions for videos that have finished.

CREATE OR REPLACE FUNCTION public.record_subtitle_stats(p_video_id text, p_channel_id text, p_language text, p_total_subtitles bigint, p_total_words bigint, p_speech_duration_ms bigint)
 RETURNS void
 LANGUAGE sql
AS $function$
    INSERT INTO public.video_subtitle_stats
        (video_id, channel_id, language, total_subtitles, total_words, speech_duration_ms,
         subtitles_per_min, words_per_min, speech_coverage_pct)
    SELECT p_video_id, p_channel_id, p_language, p_total_subtitles, p_total_words, p_speech_duration_ms,
        ROUND((p_total_subtitles / (NULLIF(v.duration,0) / 60.0))::numeric, 2),
        ROUND((p_total_words / (NULLIF(v.duration,0) / 60.0))::numeric, 2),
        ROUND((p_speech_duration_ms / 1000.0 / NULLIF(v.duration,0) * 100)::numeric, 2)
    FROM public.videos v
    WHERE v.id = p_video_id
    ON CONFLICT (video_id, language) DO UPDATE
    SET channel_id = EXCLUDED.channel_id,
        total_subtitles = EXCLUDED.total_subtitles,
        total_words = EXCLUDED.total_words,
        speech_duration_ms = EXCLUDED.speech_duration_ms,
        subtitles_per_min = EXCLUDED.subtitles_per_min,
        words_per_min = EXCLUDED.words_per_min,
        speech_coverage_pct = EXCLUDED.speech_coverage_pct;
$function$;
