-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- Per-video message stats: an incrementally-maintained rollup table (NOT a materialized view --
-- messages has 200M+ rows, so recomputing a full aggregate on every refresh doesn't scale).
-- Maintained one message at a time by public.record_message_stats(), called from
-- modules/Classes.py Get_Messages via modules/Database.py's RecordMessageStats(). See
-- sql/video_message_stats.sql for full DDL, the maintenance functions, and the one-time backfill.

-- public.video_message_stats definition

-- Drop table

-- DROP TABLE public.video_message_stats;

CREATE TABLE public.video_message_stats (
	video_id text NOT NULL,
	total_messages int8 DEFAULT 0 NOT NULL,
	messages_nonmembers int8 DEFAULT 0 NOT NULL,
	messages_members int8 DEFAULT 0 NOT NULL,
	unique_users int8 DEFAULT 0 NOT NULL,
	unique_nonmembers int8 DEFAULT 0 NOT NULL,
	unique_members int8 DEFAULT 0 NOT NULL,
	first_messages int8 DEFAULT 0 NOT NULL,
	first_channel_messages int8 DEFAULT 0 NOT NULL,
	messages_per_min numeric NULL,
	CONSTRAINT video_message_stats_pkey PRIMARY KEY (video_id),
	CONSTRAINT video_message_stats_video_id_fkey FOREIGN KEY (video_id) REFERENCES public.videos(id)
);


-- public.video_user_seen definition

-- Dedup helper: has this (video, user) pair already been counted into unique_users/members?

-- Drop table

-- DROP TABLE public.video_user_seen;

CREATE TABLE public.video_user_seen (
	video_id text NOT NULL,
	user_id text NOT NULL,
	is_member bool DEFAULT false NOT NULL,
	CONSTRAINT video_user_seen_pkey PRIMARY KEY (video_id, user_id)
);


-- Maintenance functions. record_message_stats()/record_message_stats_batch() and
-- finalize_video_message_rate() are called incrementally during chat ingestion
-- (modules/Database.py's RecordMessageStatsBatch/FinalizeVideoMessageRate, called from
-- modules/Classes.py Get_Messages, one batched call per commit). refresh_first_message_counts()
-- and refresh_user_message_rankings() are recomputed-from-scratch refreshes called once per
-- full bot run (see the end of Main.py) rather than incrementally -- see each function's own
-- history in sql/video_message_stats.sql, sql/user_first_channel_message_stats.sql, and
-- sql/user_global_message_rankings.sql for the full rationale and past incidents that shaped them.

-- public.record_message_stats definition

-- Called once per newly-inserted chat message (via record_message_stats_batch(), below --
-- not usually called directly anymore). Upserts video_message_stats totals for the message's
-- own video, the video_user_seen dedup row, and the user's global/per-channel first-message
-- pointers (user_first_message/user_first_channel_message). Deliberately never touches another
-- video's video_message_stats row -- an earlier version did, to move
-- first_messages/first_channel_messages credit between videos inline, which could deadlock two
-- worker threads processing two different videos against each other. That accounting was moved
-- out to refresh_first_message_counts() instead.

CREATE OR REPLACE FUNCTION public.record_message_stats(p_channel_id text, p_video_id text, p_user_id text, p_timestamp double precision, p_is_member boolean, p_member_status bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_prev_is_member boolean;
    v_was_new_user boolean;
BEGIN
    INSERT INTO public.video_message_stats (video_id) VALUES (p_video_id)
        ON CONFLICT (video_id) DO NOTHING;

    UPDATE public.video_message_stats
    SET total_messages = total_messages + 1,
        messages_nonmembers = messages_nonmembers + (CASE WHEN p_is_member THEN 0 ELSE 1 END),
        messages_members = messages_members + (CASE WHEN p_is_member THEN 1 ELSE 0 END)
    WHERE video_id = p_video_id;

    -- Lock any existing (video_id, user_id) row so concurrent messages for the same user
    -- in the same video (rare, but possible across reprocessing) serialize correctly.
    SELECT is_member INTO v_prev_is_member
    FROM public.video_user_seen
    WHERE video_id = p_video_id AND user_id = p_user_id
    FOR UPDATE;

    v_was_new_user := NOT FOUND;

    IF v_was_new_user THEN
        INSERT INTO public.video_user_seen (video_id, user_id, is_member)
        VALUES (p_video_id, p_user_id, p_is_member);

        UPDATE public.video_message_stats
        SET unique_users = unique_users + 1,
            unique_members = unique_members + (CASE WHEN p_is_member THEN 1 ELSE 0 END),
            unique_nonmembers = unique_nonmembers + (CASE WHEN p_is_member THEN 0 ELSE 1 END)
        WHERE video_id = p_video_id;
    ELSIF p_is_member AND NOT v_prev_is_member THEN
        UPDATE public.video_user_seen SET is_member = true
        WHERE video_id = p_video_id AND user_id = p_user_id;

        UPDATE public.video_message_stats
        SET unique_members = unique_members + 1,
            unique_nonmembers = unique_nonmembers - 1
        WHERE video_id = p_video_id;
    END IF;

    -- Global first-message pointer. Single-row upsert -- Postgres handles the read-modify-write
    -- atomically, so there's no separate lock step, and (critically) no reference to any OTHER
    -- video's video_message_stats row anymore.
    INSERT INTO public.user_first_message (user_id, video_id, "timestamp")
    VALUES (p_user_id, p_video_id, p_timestamp)
    ON CONFLICT (user_id) DO UPDATE
    SET video_id = EXCLUDED.video_id,
        "timestamp" = EXCLUDED."timestamp"
    WHERE EXCLUDED."timestamp" < public.user_first_message."timestamp";

    -- Per-channel first-message pointer, plus the per-channel totals that live on the same row
    -- (total_messages, last_message_ts, max_member_status). Same single-row-upsert treatment.
    INSERT INTO public.user_first_channel_message
        (channel_id, user_id, video_id, "timestamp", total_messages, last_message_ts, max_member_status)
    VALUES (p_channel_id, p_user_id, p_video_id, p_timestamp, 1, p_timestamp, p_member_status)
    ON CONFLICT (channel_id, user_id) DO UPDATE
    SET total_messages = public.user_first_channel_message.total_messages + 1,
        last_message_ts = GREATEST(public.user_first_channel_message.last_message_ts, EXCLUDED.last_message_ts),
        max_member_status = GREATEST(public.user_first_channel_message.max_member_status, EXCLUDED.max_member_status),
        video_id = CASE WHEN EXCLUDED."timestamp" < public.user_first_channel_message."timestamp"
            THEN EXCLUDED.video_id ELSE public.user_first_channel_message.video_id END,
        "timestamp" = LEAST(public.user_first_channel_message."timestamp", EXCLUDED."timestamp");
END;
$function$;


-- public.record_message_stats_batch definition

-- Batched wrapper around record_message_stats(), one round trip for a whole buffer
-- of calls instead of one round trip per call -- see RecordMessageStatsBatch in
-- modules/Database.py. modules/Classes.py Get_Messages buffers each message's
-- record_message_stats() args, sorts the buffer by user_id (for the same lock-order
-- reason as record_message_stats() itself), and flushes it here right before every
-- commit. One call carrying all the rows removes N-1 round trips' worth of network
-- latency from how long another worker can be blocked waiting on a contended user.

CREATE OR REPLACE FUNCTION public.record_message_stats_batch(p_channel_ids text[], p_video_ids text[], p_user_ids text[], p_timestamps double precision[], p_is_members boolean[], p_member_statuses bigint[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    i int;
BEGIN
    FOR i IN 1..array_length(p_user_ids, 1) LOOP
        PERFORM public.record_message_stats(
            p_channel_ids[i], p_video_ids[i], p_user_ids[i],
            p_timestamps[i], p_is_members[i], p_member_statuses[i]
        );
    END LOOP;
END;
$function$;


-- public.finalize_video_message_rate definition

-- Fills in video_message_stats.messages_per_min for one video once its duration is known (a
-- video's duration is NULL while it's still live). Called once per video when it finishes --
-- see FinalizeVideoMessageRate in modules/Database.py, called from Main.py's _mark_processed().

CREATE OR REPLACE FUNCTION public.finalize_video_message_rate(p_video_id text)
 RETURNS void
 LANGUAGE sql
AS $function$
    UPDATE public.video_message_stats vms
    SET messages_per_min = ROUND((vms.total_messages / (NULLIF(v.duration, 0) / 60.0))::numeric, 2)
    FROM public.videos v
    WHERE v.id = p_video_id AND vms.video_id = p_video_id;
$function$;
