-- Auto-generated by .claude/skills/chat-database/update_schema.py from the live
-- database schema -- do not hand-edit. Add rationale comments to the NARRATIVE dict
-- in that script instead, then re-run it, or they'll be lost on the next regeneration.
-- See sql/README.md for the order these files must be run in on a fresh database.

-- public.videos definition

-- subtitles_processed tracks the subtitle-download pipeline (Subtitles.py) independently
-- of the chat/video 'processed' flag above -- the two used to be coupled (subtitles were
-- only ever attempted once, inline, right after a video's chat finished), which meant a
-- throttled/failed subtitle attempt was never retried once 'processed' went true. Backfilled
-- once via backfill_subtitles_processed.py for videos that already had subtitle rows before
-- this column existed.

-- Drop table

-- DROP TABLE public.videos;

CREATE TABLE public.videos (
	id text NOT NULL,
	title text NULL,
	livestream bool NULL,
	islive bool NULL,
	processed bool DEFAULT false NOT NULL,
	publishedat timestamp NULL,
	scheduled_start timestamp NULL,
	start_time timestamp NULL,
	end_time timestamp NULL,
	duration int8 GENERATED ALWAYS AS (EXTRACT(epoch FROM (end_time - start_time))) STORED NULL,
	members bool DEFAULT false NOT NULL,
	channel_id text NOT NULL,
	subtitles_processed bool DEFAULT false NOT NULL,
	CONSTRAINT pk_videos_id PRIMARY KEY (id),
	CONSTRAINT videos_channel_directory_fk FOREIGN KEY (channel_id) REFERENCES public.channel_directory(user_id)
);
CREATE INDEX idx_videos_duration ON public.videos USING btree (duration);
CREATE INDEX idx_videos_end_time ON public.videos USING btree (end_time);
CREATE INDEX idx_videos_published ON public.videos USING btree (publishedat);
CREATE INDEX idx_videos_scheduled ON public.videos USING btree (scheduled_start);
CREATE INDEX idx_videos_start_time ON public.videos USING btree (start_time);
CREATE INDEX idx_videos_subtitles_processed ON public.videos USING btree (channel_id, members) WHERE (subtitles_processed = false);
